### ISSUE TITLE
instant crash when opening "Improved Combinator"

### ISSUE THREAD

**Issue by cloudziq** [321freddy/attach-notes#12]
there is small mod which adds a bit more advanced combinator (https://mods.factorio.com/mod/ImprovedCombinator),  it's currently crashing when opening it with Attach-Notes enabled.
Hope there is possible to have fix for that,  since I need both mods ;p

**Comment by 321freddy** [comment]
Can you paste the error message here?

**Comment by kuxynator** [comment]
I think, this is the same crash, as with other mods
- https://mods.factorio.com/mod/magic-lamp
- https://mods.factorio.com/mod/stargate
- https://mods.factorio.com/mod/integratedCircuitry

Die Mod Attach Notes (0.4.3) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event attach-notes::on_gui_opened (ID 84)
Expected camera or minimap.
stack traceback:
attach-notes/scripts/metatables.lua:49: in function 'index'
__attach-notes/scripts/entity-notes/controller.lua:89: in function 'buildGUI'
attach-notes/scripts/entity-notes/controller.lua:30: in function 'func'
attach-notes/framework.lua:98: in function <attach-notes/framework.lua:97>
stack traceback:
[C]: in function 'index'
__attach-notes/scripts/metatables.lua:49: in function 'index'
__attach-notes/scripts/entity-notes/controller.lua:89: in function 'buildGUI'
attach-notes/scripts/entity-notes/controller.lua:30: in function 'func'
attach-notes/framework.lua:98: in function <attach-notes/framework.lua:97>

**Comment by 321freddy** [comment]
> 
> 
> there is small mod which adds a bit more advanced combinator (https://mods.factorio.com/mod/ImprovedCombinator), it's currently crashing when opening it with Attach-Notes enabled.
> Hope there is possible to have fix for that, since I need both mods ;p

Fixed for next version.


> 
> 
> I think, this is the same crash, as with other mods
> 
>     * https://mods.factorio.com/mod/magic-lamp
> 
>     * https://mods.factorio.com/mod/stargate
> 
>     * https://mods.factorio.com/mod/integratedCircuitry
> 
> 
> Die Mod Attach Notes (0.4.3) hat einen Fehler verursacht, der nicht behoben werden kann.
> Bitte informiere den Autor der Mod über diesen Fehler.
> 
> Error while running event attach-notes::on_gui_opened (ID 84)
> Expected camera or minimap.
> stack traceback:
> attach-notes/scripts/metatables.lua:49: in function 'index'
> __attach-notes/scripts/entity-notes/controller.lua:89: in function 'buildGUI'
> attach-notes/scripts/entity-notes/controller.lua:30: in function 'func'
> attach-notes/framework.lua:98: in function <attach-notes/framework.lua:97>
> stack traceback:
> [C]: in function 'index'
> __attach-notes/scripts/metatables.lua:49: in function 'index'
> __attach-notes/scripts/entity-notes/controller.lua:89: in function 'buildGUI'
> attach-notes/scripts/entity-notes/controller.lua:30: in function 'func'
> attach-notes/framework.lua:98: in function <attach-notes/framework.lua:97>

Magic lamp and integratedCircuitry fixed aswell.
Stargate error is not related to attach notes.
