### ISSUE TITLE
signpost `ghosts` can't be build on

### ISSUE THREAD

**Issue by cloudziq** [321freddy/attach-notes#14]
when you copy a signpost and place a ghost of it,  or destroy one to leave ghost - there is no way to place a new signpost on top of that ghost

**Comment by cloudziq** [comment]
This is probably very related,  but if you destroy the signpost, there is no way to build anything on its place, very frustrating.  creating a blueprint with that spot shows that there is still a 'note' there

**Comment by 321freddy** [comment]
I fixed the leftover notes when destroying a signpost for the next version.
