### ISSUE TITLE
Using select new content blueprint feature breaks notes in entities.

### ISSUE THREAD

**Issue by m4v** [321freddy/attach-notes#15]
If I create a new blueprint with an attached note in an entity, placing the blueprint works as expected. If however you use the "select new contents" button for modify an existing blueprint, placing it will not add the notes and will show as "missing material for construction".

**Comment by 321freddy** [comment]
I'm having a hard time to reproduce this. What materials are shown as missing? And can you maybe post the BP-String for me to test it.

**Comment by m4v** [comment]
![Captura de pantalla de 2020-10-31 21-57-02](https://user-images.githubusercontent.com/43076/97792983-47f96a00-1bc4-11eb-8886-8e0d4cb236cf.png)

You can see the missing materials alert, this is the BP-string that gives that error:

`0eNqFkN1qhEAMhd8l12NxxJ+ur1KWZbTZNqAZGaNUZN69GRdkoZS9S8LJdw5nh25YcArEAu0O1Hueof3YYaYvdkO6yTYhtECCIxhgN6bt/MrYC2Y6YLi7HiEaIP7EH2htvBpAFhLCB/NYthsvY4dBBSctuYpTWO/HjtiJD2o1+Vl/PacQiWert8rABm1mcx1jNH+QxeuAr7km5ZHgh1uH324lDaPKOw2K+KeclYIsejntH4osh4O2pHYvTV0Xl/K5n5gqOop9CqyQVY2OgMW7LZtSPxub11Ud4y8BNo8Q`

Be aware that this blueprint was created by using the "select new contents" button of an existing blueprint, creating a new blueprint doesn't cause problem. 

Edit: I realise now that how I worded the issue before it was not clear how I was editing the blueprint.

**Comment by m4v** [comment]
Step by step to reproduce:

1. Place a constant combinator, and attach a note to it.
2. Create a new blueprint with this constant combinator.
3. Test that the blueprint works, placing it anywhere creates a new combinator with the attached note.
4. Now open the edit dialog for this blueprint.
5. Press the "select new blueprint contents" button.
6. Select again the same constant combinator for change the blueprint.
7. Place the edited blueprint anywhere, now the combinator is missing the note and the note itself is a "missing material for construction"

**Comment by 321freddy** [comment]
Fixed in version 0.5.0. The blueprints were saved incorrectly so the notes are gone sadly, but it shouldn't happen again. Thanks for the detailed report.
