### ISSUE TITLE
Mod crashes server - 'Unknown sprite "item/signal-unknown"'

### ISSUE THREAD

**Issue by DatenNirwana** [321freddy/attach-notes#16]
Hi,

the mod crashed the server with the following exception:

`426.228 Error MainLoop.cpp:1207: Exception at tick 227284581: The mod Attach Notes (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event attach-notes::on_selected_entity_changed (ID 52)
Unknown sprite "item/signal-unknown"
stack traceback:
        __attach-notes__/scripts/entity-notes/gui-templates.lua:500: in function 'onCreated'
        __attach-notes__/scripts/entity-notes/gui-templates.lua:175: in function 'onCreated'
        __attach-notes__/scripts/gui-tools.lua:149: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/entity-notes/controller.lua:82: in function 'buildPreviewGUI'
        __attach-notes__/scripts/entity-notes/controller.lua:70: in function 'func'
        __attach-notes__/framework.lua:98: in function <__attach-notes__/framework.lua:97>
stack traceback:
        [C]: in function '__newindex'
        __attach-notes__/scripts/entity-notes/gui-templates.lua:500: in function 'onCreated'
        __attach-notes__/scripts/entity-notes/gui-templates.lua:175: in function 'onCreated'
        __attach-notes__/scripts/gui-tools.lua:149: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/entity-notes/controller.lua:82: in function 'buildPreviewGUI'
        __attach-notes__/scripts/entity-notes/controller.lua:70: in function 'func'
        __attach-notes__/framework.lua:98: in function <__attach-notes__/framework.lua:97>
 426.230 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod Attach Notes (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event attach-notes::on_selected_entity_changed (ID 52)
Unknown sprite "item/signal-unknown"
stack traceback:
        __attach-notes__/scripts/entity-notes/gui-templates.lua:500: in function 'onCreated'
        __attach-notes__/scripts/entity-notes/gui-templates.lua:175: in function 'onCreated'
        __attach-notes__/scripts/gui-tools.lua:149: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/entity-notes/controller.lua:82: in function 'buildPreviewGUI'
        __attach-notes__/scripts/entity-notes/controller.lua:70: in function 'func'
        __attach-notes__/framework.lua:98: in function <__attach-notes__/framework.lua:97>
stack traceback:
        [C]: in function '__newindex'
        __attach-notes__/scripts/entity-notes/gui-templates.lua:500: in function 'onCreated'
        __attach-notes__/scripts/entity-notes/gui-templates.lua:175: in function 'onCreated'
        __attach-notes__/scripts/gui-tools.lua:149: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/gui-tools.lua:145: in function 'create'
        __attach-notes__/scripts/entity-notes/controller.lua:82: in function 'buildPreviewGUI'
        __attach-notes__/scripts/entity-notes/controller.lua:70: in function 'func'
        __attach-notes__/framework.lua:98: in function <__attach-notes__/framework.lua:97>"
 426.230 Info ServerMultiplayerManager.cpp:769: updateTick(227284581) changing state from(InGame) to(Failed)
 426.239 Quitting: multiplayer error.
 428.718 Info ServerMultiplayerManager.cpp:136: Quitting multiplayer connection.
 428.718 Info ServerMultiplayerManager.cpp:769: updateTick(4294967295) changing state from(Failed) to(Closed)
 429.092 Info UDPSocket.cpp:218: Closing socket
 429.093 Info UDPSocket.cpp:248: Socket closed
 429.096 Goodbye
`

**Comment by 321freddy** [comment]
Fixed in version 0.5.0
