### ISSUE TITLE
FNEI Crashes when combined with both Attach Notes and Bob's Metals

### ISSUE THREAD

**Issue by Kiefy** [321freddy/attach-notes#4]
Not sure if I should report this to ![FNEI](https://github.com/npo6ka/FNEI), but since we've become such good friends today (Thanks for the Lightning-Fast Creative mode fix! 😃), I thought I'd run it by you first. 😁

Tested with only:
- attach-notes_0.1.1
- ![boblibrary_0.16.1](https://mods.factorio.com/mods/Bobingabout/boblibrary)
- ![bobplates_0.16.0](https://mods.factorio.com/mods/Bobingabout/bobplates)
- ![FNEI_0.0.16](https://mods.factorio.com/mods/npo6ka/FNEI)

Remove attach notes or Bob's and it's fine, but when both together. all hell breaks loose!

To reproduce:
- Open FNEI with Ctrl-E, and type "tu" in the search box.
![](https://image.prntscr.com/image/pkbo7QYnT12FB4UkcBjkkA.png)

**Comment by Kiefy** [comment]
Just tested attach notes 0.1.2 just in case. still same.  I can confirm the Creative mode issue is solved though. :)

**Comment by 321freddy** [comment]
This is an FNEI issue. I reported it here: https://github.com/npo6ka/FNEI/issues/12
