### ISSUE TITLE
Got the following error when blueprinting Decider Combinators with notes added to it

### ISSUE THREAD

**Issue by Be-Cool-Man** [321freddy/attach-notes#5]
Error while running event attach-notes::on_gui_closed (ID 84)
    Invalid destination circuit connector ID: 2
    stack traceback:
    	__attach-notes__/scripts/entity-notes/controller.lua:299: in function 'filterStorages'
    	__attach-notes__/scripts/entity-notes/controller.lua:46: in function 'func'
    	__attach-notes__/control.lua:95: in function <__attach-notes__/control.lua:94>

**Active Mods**
* 5dim_autofill_0.16.0.zip
* 5dim_automatization_0.16.4.zip
* 5dim_battlefield_0.16.7.zip
* 5dim_botrecaller_0.16.2.zip
* 5dim_core_0.16.5.zip
* 5dim_decoration_0.16.2.zip
* 5dim_energy_0.16.6.zip
* 5dim_equipment_0.16.3.zip
* 5dim_infiniteresearch_0.16.5.zip
* 5dim_logistic_0.16.4.zip
* 5dim_mining_0.16.6.zip
* 5dim_module_0.16.3.zip
* 5dim_nuclear_0.16.4.zip
* 5dim_ores_0.16.7.zip
* 5dim_resources_0.16.7.zip
* 5dim_trade_0.16.2.zip
* 5dim_trains_0.16.5.zip
* 5dim_transport_0.16.5.zip
* 5dim_vehicle_0.16.3.zip
* AtomicArtillery_0.1.5.zip
* attach-notes_0.1.2.zip
* BigDrills_0.5.1.zip
* boblibrary_0.16.1.zip
* creative-mode-fix_0.0.18.zip
* ElectricTrain_0.16.2.zip
* Flow Control_3.0.3.zip
* FNEI_0.0.17.zip
* Helicopters_0.2.12.zip
* Infinizoom_0.1.2.zip
* LoaderRedux_1.2.2.zip
* LogisticTrainNetwork_1.6.4.zip
* mod-list.json
* mod-settings.json
* MushroomCloud_1.0.2.zip
* NapalmArtillery_0.16.1.zip
* Noxys_Trees_0.0.10.zip
* OmegaDrill_0.1.5.zip
* radarplus for rso_0.0.5.zip
* rso-mod_3.5.4.zip
* StorageTank2_0.3.0.zip
* Subterranean_0.5.0.zip
* timed_technology_0.0.5.zip
* UltimateBelts_0.16.2.zip
* upgrade-planner_1.5.2.zip
* vtk-ta-big-bertha-artillery-sounds_1.1.0.zip
* Warehousing_0.1.0.zip
* Wind_Turbine V16_4.0.1.zip

**Comment by 321freddy** [comment]
Fixed for version 0.1.3, I will upload it soon. Make sure to update the mod.
