### ISSUE TITLE
Conflict with Train Supply Manager

### ISSUE THREAD

**Issue by Be-Cool-Man** [321freddy/attach-notes#6]
I'm getting the following message when i try to load Factorio with _Attach Notes_ and _[Train Supply Manager](https://mods.factorio.com/mod/train-pubsub)_:

> Error loading mods
> 
> Failed to load mods: Error while running setup for entity prototype "train-counter" (constant-combinator): No order string defined and there is no item to place it.
> 
> Mods to be disabled:
> → train-pubsub
> → Squeak Through
> → attach-notes

I [reported](https://mods.factorio.com/mod/train-pubsub/discussion/5c0a8717d7dbac000b17995d) this error to LordKTor (author from Train Supply Manager) but he said his mod is not the culprit and pointet at Attach Notes.

**Comment by 321freddy** [comment]
I can look into this, but you will have to wait as I am currently very busy.

**Comment by Be-Cool-Man** [comment]
I understand, and i have the patience to wait. As you can see at my response time… I'm very busy too.

**Comment by 321freddy** [comment]
Fixed in 0.2.6
