### ISSUE TITLE
Fix factorio version 0.17

### ISSUE THREAD

**Issue by navoznov** [321freddy/attach-notes#7]
fix factorio version compatibility for version 0.17

**Comment by 321freddy** [comment]
I will update it eventually, but a lot is going to change. I'll remove the blueprint notes, as it will be integrated into the base game soon. Also the modding API has been improved significantly, so the mod can be improved significantly as well, but this stuff takes time, which is scarce on my side.

**Comment by 321freddy** [comment]
Updated to 0.17, but it is no longer possible to blueprint notes on entities as the new modding API made it impossible.
If you want this feature tell the devs to implement this request: https://forums.factorio.com/viewtopic.php?f=28&t=70315
