### ISSUE TITLE
blueprint don't copy notes with it

### ISSUE THREAD

**Issue by judos** [321freddy/attach-notes#8]
Hi there,
Awesome mod!

However currently it seems on factoiro 0.17.66 attached notes of entities aren't copied when I copy buildings with copy&paste or blueprint function. This would be very cool.

Thanks for your help!

**Comment by 321freddy** [comment]
This was possible in 0.16, but in 0.17 the devs broke the way the mod saved the notes in blueprints, so it's no longer possible.

**Comment by judos** [comment]
May I ask how you did this in 0.16?
I personally wrote the mod beltSorter where I copy settings as well and I have some idea how it would be possible to copy notes with blueprints as well.
Basically you could mod a constant-combinator which is invisible and build it for every note so it gets copied as well. Signals can of course only store numbers, but you could put every text in a list and then just save the index of your text on the combinator. When the note building is rebuilt from ghost it checks if there's your modded combinator on the same position and if so takes over the text that was stored at the specific index...

I don't know of what type your attached notes are, eventually they could be combinators themselves, so you don't need an additional entity etc...

If you want to implement it and need help feel free to ask. I'm also in discord on the factorio server mostly on evenings (UTC+1)

**Comment by 321freddy** [comment]
In 0.16 the notes were saved in invisible programmable speakers inside their alert message, but in 0.17 the msg is capped. It is possible to encode the msg in constant combinators, but number of signals is also capped. Rewriting the mod to use multiple entities for saving a note is possible, but it's a nightmare to code which I currently have no time for.

**Comment by fstd** [comment]
How about train stops?  Their names are capped at a somewhat more generous 1024 characters.  Capping notes to 1024 chars sounds better than not being able to blueprint signposts at all.
